<?xml version="1.0"?>
<package format="3">
  <name>ika_sensors</name>
  <version>0.0.1</version>
  <description>Sensor publisher package for TEKNOFEST autonomous ground vehicle.</description>

  <maintainer email="sukru.birim@gmail.com">sukru</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>ika_msgs</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <exec_depend>v4l2_camera</exec_depend>
  <exec_depend>rplidar_ros</exec_depend>
  <exec_depend>imu_filter_madgwick</exec_depend>
  <exec_depend>nmea_navsat_driver</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>